# Generated by Django 3.1.3 on 2020-11-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
