# Generated by Django 3.1.3 on 2020-11-14 06:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201111_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='excpert',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
